### ISSUE TITLE
No whatsapp notifications on Samsung Gear S2

### ISSUE THREAD

**Issue by coolfire77** [Nevolution/sdk#13]
Though the gear s2 is connected to my Galaxy Note 4, whatsapp notifications don't get sent through to the watch. Uninstalling Nevolution will make then work again.

Smses and phonecalls still manage to send their notifications through to the Gear S2.

**Comment by oasisfeng** [comment]
I'm not sure how does Gear S2 sync notification to your watch since I don't have this gear and it's also proprietary system other than Android Wear. Please check whether Nevolution and the Ext pack are blocked in the notification settings of your watch.

If WhatsApp messages are handled differently than other notifications, there's a high chance that it may not compatible with Nevolution.

**Comment by coolfire77** [comment]
Hello! Thank you for your quick reply and great enthusiasm on all your apps!
Just a fyi, the Gear S2 does not have any settings from the watch for notifications, which I think it's because it is Tizen--powered. However, all notification controls are down via Samsung's app called Samsung Gear: https://play.google.com/store/apps/details?id=com.samsung.android.app.watchmanager.
I also believe that once the whatsapp notification sound issue is solved, the notification can also go through to the watch. Maybe Nevolution somehow "half-blocks" whatsapp notifications? :p
