### ISSUE TITLE
Sound Modification Possible?

### ISSUE THREAD

**Issue by shellscape** [Nevolution/sdk#14]
I found Nevolution as I was searching for an app to override notification sounds per app. The few that I tested were doing some funky "dialing home" though I couldn't tell what the data was exactly. I'd rather not run a firewall to block net access just for those apps, so they got the boot. 

On to Nevolution - it seems like a wonderful platform for doing exactly what I was after. And I'm curious if this platform would allow for that. I'm willing to do the development to bring the feature to the app via a plugin, but is it even possible?

**Comment by oasisfeng** [comment]
That's a feature I'm planning to add, but at a cost. Due to the intrinsic delay before notification's arrival at Nevolution, the only viable solution is turning off sound and vibration of all notifications as a whole and change & replay them in Nevolution. Unfortunately this breaks a foundation principle in Nevolution - Never affect notifications without explicitly configured rules.

**Comment by oasisfeng** [comment]
If the sound of notification could be turned off in the source app, then a plug-in can easily add custom sound on top of it.

**Comment by oasisfeng** [comment]
Nevolution 2.0 support notification channel of Android 8+, which can be attached to notifications even if the original app does not support channels. This is the perfect solution for sound customization.

See sample decorator [WeChat Modernized](https://github.com/Nevolution/decorator-wechat) for example.
